name: selfbot
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - pocketbase:/backend/pb_data

volumes:
  pocketbase: